spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      # Для автоматического перевода Timestamp в нужную временную зону
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
# Для отображения дополнительных логов
logging:
  level:
    org:
      springframework:
        security: debug