version: '1'
services:
  postgres:
    container_name: your-rating_db
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
  sonar:
    image: sonarqube:10.2.1-community
    ports:
      - '9000:9000'